import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
const output = new URL('./artifacts/', import.meta.url).pathname.replace(/^\/([A-Z]:)/, '$1');
await mkdir(output, { recursive: true });
const browser = await chromium.launch({ headless: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 1100 }, deviceScaleFactor: 1 });
const page = await context.newPage();
const errors = [];
page.on('pageerror', error => errors.push(error.message));
await page.clock.install({ time: new Date('2026-09-22T00:00:00Z') });
await page.clock.pauseAt(new Date('2026-09-22T00:00:01Z'));
try {
  await page.goto(process.env.POC_URL || 'http://127.0.0.1:4187', { waitUntil: 'networkidle' });
  await page.clock.runFor(100);
  await page.screenshot({ path: `${output}/desktop.png`, fullPage: true });
  await page.locator('#demo-tools-toggle').click();
  await page.locator('#scenario-select').selectOption('12');
  await page.locator('#ride-button').click();
  assert.equal(await page.locator('#balance').textContent(), '990.00');
  assert.match(await page.locator('#ride-action').textContent(), /참가 취소/);
  await page.locator('#ride-button').click();
  assert.equal(await page.locator('#balance').textContent(), '1,000.00');
  await page.locator('#ride-button').click();
  await page.clock.runFor(9500);
  assert.match(await page.locator('#ride-action').textContent(), /캐시아웃/);
  await page.locator('#ride-button').click();
  assert.match(await page.locator('#result-kicker').textContent(), /PERSONAL BEST/);
  assert.equal(await page.locator('#ride-button').isDisabled(), true);
  await page.locator('#demo-tools-toggle').click();
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: `${output}/cashout.png`, fullPage: true });
  await page.clock.runFor(24000);
  await page.locator('[data-view="records"]').click();
  assert.equal(await page.locator('#record-table tr').count(), 1);
  assert.match(await page.locator('#record-table').textContent(), /12.00×/);
  await page.screenshot({ path: `${output}/records.png`, fullPage: true });
  await page.locator('#back-to-play').click();
  await page.locator('[data-theme="sunset"]').click();
  assert.match(await page.locator('#theme-title').textContent(), /SUNSET/);
  await page.locator('[data-board="#f2977d"]').click();
  await page.locator('#finish-select').selectOption('spray');
  await page.locator('#help-button').click();
  assert.equal(await page.locator('#info-dialog').isVisible(), true);
  await page.locator('.dialog-close').click();
  await page.locator('#view-all-crew').click();
  assert.ok(await page.locator('#dialog-content .crew-row').count() >= 6);
  await page.locator('.dialog-close').click();
  while ((await page.locator('#ride-action').textContent()) !== '파도에 합류하기') await page.clock.runFor(500);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator('#demo-tools-toggle').click();
  await page.locator('#scenario-select').selectOption('2.5');
  await page.locator('#demo-tools-toggle').click();
  await page.locator('#ride-button').click();
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.clock.runFor(8200);
  const cashoutBox = await page.locator('#ride-button').boundingBox();
  assert.ok(cashoutBox.y > 0 && cashoutBox.y + cashoutBox.height <= 844, 'Mobile cashout stays inside the viewport');
  await page.screenshot({ path: `${output}/mobile-live.png`, fullPage: false });
  await page.locator('#ride-button').click();
  while ((await page.locator('#ride-action').textContent()) !== '파도에 합류하기') await page.clock.runFor(500);
  // Instant crash is selected from the visible QA controls, not injected engine state.
  await page.locator('#demo-tools-toggle').click();
  await page.locator('#scenario-select').selectOption('1');
  await page.locator('#ride-button').click();
  await page.clock.runFor(8100);
  assert.match(await page.locator('#result-kicker').textContent(), /WIPEOUT/);
  assert.match(await page.locator('#result-description').textContent(), /지급액 0.00 CR/);
  await page.locator('#demo-tools-toggle').click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.clock.runFor(100);
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: `${output}/mobile.png`, fullPage: true });
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth);
  assert.equal(overflow, false, 'Mobile page must not overflow horizontally');
  while ((await page.locator('#ride-action').textContent()) !== '파도에 합류하기') await page.clock.runFor(500);
  await page.locator('[data-amount="25"]').click();
  await page.locator('#ride-button').click();
  await page.reload({ waitUntil: 'networkidle' });
  await page.clock.runFor(100);
  assert.equal(await page.locator('#bet-amount').isDisabled(), false);
  assert.match(await page.locator('#theme-title').textContent(), /SUNSET/);
  assert.equal(await page.locator('#finish-select').inputValue(), 'spray');
  assert.equal(await page.locator('[data-board="#f2977d"]').getAttribute('aria-pressed'), 'true');
  await page.locator('[data-view="records"]').click();
  assert.equal(await page.locator('#record-table tr').count(), 3);
  assert.deepEqual(errors, []);
  console.log('Browser checks passed: join/cancel, cashout, best, records, crew, help, themes, finish, instant crash, reload, mobile overflow.');
  console.log(`Screenshots: ${output}`);
} finally { await browser.close(); }
